apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
    {{- include "observability.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: ui
              containerPort: 16686
          resources:
            {{- toYaml .Values.jaeger.resources | nindent 12 }}
