# SonarCloud configuration for AutoReparos

sonar.projectKey=AutoReparos
sonar.projectName=AutoReparos

# Specify source and test directories for analysis
sonar.sources=AutoReparos.API,AutoReparos.Application,AutoReparos.Domain,AutoReparos.Infra
sonar.tests=AutoReparos.Application.Tests,AutoReparos.Domain.Tests,AutoReparos.IntegrationTests

# Encoding
sonar.sourceEncoding=UTF-8
