replicaCount: 2

image:
  repository: autoreparos-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

postgres:
  image: postgres:16
  database: autoreparos
  user: admin
  password: ""
  storageSize: 2Gi
  persistence:
    enabled: true
    storageClass: "hostpath" # Definir como "gp3" no AWS EKS (CSI dynamic driver) ou "hostpath" / "" para local


config:
  aspnetcoreEnvironment: "Development"
  jwtExpiryHours: "2"
  seedUserEmail: "admin@autoreparos.com"
  sendGridFromEmail: "noreply@autoreparos.com"
  sendGridFromName: "AutoReparos"
  appBaseUrl: "http://autoreparos.local"

secrets:
  jwtSecret: ""
  seedUserPassword: ""
  aprovacaoTokenSecret: ""
  sendGridApiKey: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 40
