apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s.fullname" . }}-api
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s.selectorLabels" . | nindent 6 }}
      app: {{ include "k8s.fullname" . }}-api
  template:
    metadata:
      labels:
        {{- include "k8s.selectorLabels" . | nindent 8 }}
        app: {{ include "k8s.fullname" . }}-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1654
        runAsGroup: 1654
        fsGroup: 1654
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1654
            runAsGroup: 1654
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.config.aspnetcoreEnvironment | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s.fullname" . }}-secrets
                  key: postgres-password
            - name: ConnectionStrings__DbConnection
              value: "Host={{ include "k8s.fullname" . }}-postgres-service;Database={{ .Values.postgres.database }};Username={{ .Values.postgres.user }};Password=$(POSTGRES_PASSWORD)"
            - name: Jwt__ExpiryHours
              valueFrom:
                configMapKeyRef:
                  name: {{ include "k8s.fullname" . }}-config
                  key: Jwt__ExpiryHours
            - name: SeedUser__Email
              valueFrom:
                configMapKeyRef:
                  name: {{ include "k8s.fullname" . }}-config
                  key: SeedUser__Email
            - name: SendGrid__FromEmail
              valueFrom:
                configMapKeyRef:
                  name: {{ include "k8s.fullname" . }}-config
                  key: SendGrid__FromEmail
            - name: SendGrid__FromName
              valueFrom:
                configMapKeyRef:
                  name: {{ include "k8s.fullname" . }}-config
                  key: SendGrid__FromName
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s.fullname" . }}-secrets
                  key: Jwt__Secret
            - name: SeedUser__Password
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s.fullname" . }}-secrets
                  key: SeedUser__Password
            - name: AprovacaoToken__Secret
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s.fullname" . }}-secrets
                  key: AprovacaoToken__Secret
            - name: SendGrid__ApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "k8s.fullname" . }}-secrets
                  key: SendGrid__ApiKey
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
