apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "k8s.fullname" . }}-postgres-pv
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.postgres.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/postgres"
