{{- if .Values.postgres.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s.fullname" . }}-postgres-pvc
  labels:
    {{- include "k8s.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if and (not (empty .Values.postgres.persistence.storageClass)) (ne .Values.postgres.persistence.storageClass "hostpath") }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- else }}
  volumeName: {{ include "k8s.fullname" . }}-postgres-pv
  storageClassName: ""
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
{{- end }}

